import Foundation

public protocol SchemaCreativeWork: Thing, CreativeWorkOrURL, CreativeWorkOrText, CreativeWorkOrProductOrURL {
    var about: Thing? { get set }
    var accessMode: AccessMode? { get set }
    var accessModeSufficient: [AccessModeSufficient]? { get set }
    var accessibilityAPI: AccessibilityAPI? { get set }
    var accessibilityControl: AccessibilityControl? { get set }
    var accessibilityFeature: AccessibilityFeature? { get set }
    var accessibilityHazard: AccessibilityHazard? { get set }
    var accessibilitySummary: String? { get set }
    var accountablePerson: SchemaPerson? { get set }
    var aggregateRating: SchemaAggregateRating? { get set }
    var alternativeHeadline: String? { get set }
    var associatedMedia: SchemaMediaObject? { get set }
    var audience: SchemaAudience? { get set }
    var audio: SchemaAudioObject? { get set }
    var author: OrganizationOrPerson? { get set }
    var award: String? { get set }
    var character: SchemaPerson? { get set }
    var citation: CreativeWorkOrText? { get set }
    var comment: SchemaComment? { get set }
    var commentCount: Int? { get set }
    var contentLocation: SchemaPlace? { get set }
    var contentRating: String? { get set }
    var contributor: OrganizationOrPerson? { get set }
    var copyrightHolder: OrganizationOrPerson? { get set }
    var copyrightYear: Int? { get set }
    var creator: OrganizationOrPerson? { get set }
    var dateCreated: DateOnlyOrDateTime? { get set }
    var dateModified: DateOnlyOrDateTime? { get set }
    var datePublished: DateOnly? { get set }
    var discussionURL: URL? { get set }
    var editor: SchemaPerson? { get set }
    var educationalAlignment: SchemaAlignmentObject? { get set }
    var educationalUse: String? { get set }
    var encoding: SchemaMediaObject? { get set }
    var exampleOfWork: SchemaCreativeWork? { get set }
    var fileFormat: TextOrURL?  { get set }
    var funder: OrganizationOrPerson?  { get set }
    var genre: TextOrURL?  { get set }
    var hasPart: SchemaCreativeWork?  { get set }
    var headline: String?  { get set }
    var inLanguage: LanguageOrText?  { get set }
    var interactionStatistic: SchemaInteractionCounter?  { get set }
    var interactivityType: Interactivity?  { get set }
    var isAccessibleForFree: Bool?  { get set }
    var isBasedOn: CreativeWorkOrProductOrURL?  { get set }
    var isFamilyFriendly: Bool?  { get set }
    var isPartOf: SchemaCreativeWork?  { get set }
    var keywords: String?  { get set }
    var learningResourceType: String?  { get set }
    var license: CreativeWorkOrURL?  { get set }
    var locationCreated: SchemaPlace?  { get set }
    var mainEntity: Thing?  { get set }
    var material: ProductOrTextOrURL?  { get set }
    var mentions: Thing?  { get set }
    var offers: [SchemaOffer]?  { get set }
    var position: IntegerOrText?  { get set }
    var producer: OrganizationOrPerson?  { get set }
    var provider: OrganizationOrPerson?  { get set }
    var releasedEvent: SchemaPublicationEvent?  { get set }
    var review: SchemaReview?  { get set }
    var schemaVersion: TextOrURL?  { get set }
    var sourceOrganization: SchemaOrganization?  { get set }
    var spatialCoverage: SchemaPlace?  { get set }
    var sponsor: OrganizationOrPerson?  { get set }
    var temporalCoverage: DateTimeOrTextOrURL?  { get set }
    var text: String?  { get set }
    var thumbnailURL: URL?  { get set }
    var timeRequired: Duration?  { get set }
    var translator: OrganizationOrPerson?  { get set }
    var typicalAgeRange: String?  { get set }
    var version: IntegerOrText?  { get set }
    var video: SchemaVideoObject?  { get set }
    var workExample: SchemaCreativeWork?  { get set }
}

