import Foundation

public protocol SchemaCreativeWork: SchemaThing, SchemaCreativeWorkOrURL, SchemaCreativeWorkOrText, SchemaCreativeWorkOrProductOrURL {
    var about: SchemaThing? { get set }
    var accessMode: AccessMode? { get set }
    var accessModeSufficient: [AccessModeSufficient]? { get set }
    var accessibilityAPI: AccessibilityAPI? { get set }
    var accessibilityControl: AccessibilityControl? { get set }
    var accessibilityFeature: AccessibilityFeature? { get set }
    var accessibilityHazard: AccessibilityHazard? { get set }
    var accessibilitySummary: String? { get set }
    var accountablePerson: SchemaPerson? { get set }
    var aggregateRating: SchemaAggregateRating? { get set }
    var alternativeHeadline: String? { get set }
    var associatedMedia: SchemaMediaObject? { get set }
    var audience: SchemaAudience? { get set }
    var audio: SchemaAudioObject? { get set }
    var author: SchemaOrganizationOrPerson? { get set }
    var award: String? { get set }
    var character: SchemaPerson? { get set }
    var citation: SchemaCreativeWorkOrText? { get set }
    var comment: SchemaComment? { get set }
    var commentCount: Int? { get set }
    var contentLocation: SchemaPlace? { get set }
    var contentRating: String? { get set }
    var contributor: SchemaOrganizationOrPerson? { get set }
    var copyrightHolder: SchemaOrganizationOrPerson? { get set }
    var copyrightYear: Int? { get set }
    var creator: SchemaOrganizationOrPerson? { get set }
    var dateCreated: SchemaDateOrDateTime? { get set }
    var dateModified: SchemaDateOrDateTime? { get set }
    var datePublished: SchemaDate? { get set }
    var discussionURL: URL? { get set }
    var editor: SchemaPerson? { get set }
    var educationalAlignment: SchemaAlignmentObject? { get set }
    var educationalUse: String? { get set }
    var encoding: SchemaMediaObject? { get set }
    var exampleOfWork: SchemaCreativeWork? { get set }
    var fileFormat: SchemaTextOrURL?  { get set }
    var funder: SchemaOrganizationOrPerson?  { get set }
    var genre: SchemaTextOrURL?  { get set }
    var hasPart: SchemaCreativeWork?  { get set }
    var headline: String?  { get set }
    var inLanguage: SchemaLanguageOrText?  { get set }
    var interactionStatistic: SchemaInteractionCounter?  { get set }
    var interactivityType: Interactivity?  { get set }
    var isAccessibleForFree: Bool?  { get set }
    var isBasedOn: SchemaCreativeWorkOrProductOrURL?  { get set }
    var isFamilyFriendly: Bool?  { get set }
    var isPartOf: SchemaCreativeWork?  { get set }
    var keywords: String?  { get set }
    var learningResourceType: String?  { get set }
    var license: SchemaCreativeWorkOrURL?  { get set }
    var locationCreated: SchemaPlace?  { get set }
    var mainEntity: SchemaThing?  { get set }
    var material: SchemaProductOrTextOrURL?  { get set }
    var mentions: SchemaThing?  { get set }
    var offers: [SchemaOffer]?  { get set }
    var position: SchemaIntegerOrText?  { get set }
    var producer: SchemaOrganizationOrPerson?  { get set }
    var provider: SchemaOrganizationOrPerson?  { get set }
    var releasedEvent: SchemaPublicationEvent?  { get set }
    var review: SchemaReview?  { get set }
    var schemaVersion: SchemaTextOrURL?  { get set }
    var sourceOrganization: SchemaOrganization?  { get set }
    var spatialCoverage: SchemaPlace?  { get set }
    var sponsor: SchemaOrganizationOrPerson?  { get set }
    var temporalCoverage: SchemaDateTimeOrTextOrURL?  { get set }
    var text: String?  { get set }
    var thumbnailURL: URL?  { get set }
    var timeRequired: SchemaDuration?  { get set }
    var translator: SchemaOrganizationOrPerson?  { get set }
    var typicalAgeRange: String?  { get set }
    var version: SchemaIntegerOrText?  { get set }
    var video: SchemaVideoObject?  { get set }
    var workExample: SchemaCreativeWork?  { get set }
}

