import Foundation
import SOSwiftVocabulary

/// A service provided by an organization, e.g. delivery service, print services, etc.
public class SOService: SOIntangible, Service {
    
    public override class var type: String {
        return "Service"
    }
    
    /// The overall rating, based on a collection of reviews or ratings, of the item.
    public var aggregateRating: AggregateRating?
    /// The geographic area where a service or offered item is provided.
    public var areaServed: AreaServed?
    /// An intended audience, i.e. a group for whom something was created.
    public var audience: Audience?
    /// A means of accessing the service (e.g. a phone bank, a web site, a location, etc.).
    public var availableChannel: ServiceChannel?
    /// An award won by or for this item.
    public var award: [String]?
    /// The brand(s) associated with a product or service, or the brand(s) maintained by an organization or business person.
    public var brand: [BrandOrOrganization]?
    /// An entity that arranges for an exchange between a buyer and a seller. In most cases a broker never acquires or releases ownership of a product or service involved in an exchange. If it is not clear whether an entity is a broker, seller, or buyer, the latter two terms are preferred.
    public var broker: OrganizationOrPerson?
    /// A category for the item. Greater signs or slashes can be used to informally indicate a category hierarchy.
    public var category: TextOrThing?
    /// Indicates an OfferCatalog listing for this Organization, Person, or Service.
    public var hasOfferCatalog: OfferCatalog?
    /// The hours during which this service or contact is available.
    public var hoursAvailable: [OpeningHoursSpecification]?
    /// A pointer to another, somehow related product (or multiple products).
    public var isRelatedTo: [ProductOrService]?
    ///A pointer to another, functionally similar product (or multiple products).
    public var isSimilarTo: [ProductOrService]?
    /// An associated logo.
    public var logo: ImageObjectOrURL?
    /// An offer to provide this item—for example, an offer to sell a product, rent the DVD of a movie, perform a service, or give away tickets to an event.
    public var offers: [Offer]?
    /// The service provider, service operator, or service performer; the goods producer. Another party (a seller) may offer those services or goods on behalf of the provider. A provider may also serve as the seller.
    public var provider: OrganizationOrPerson?
    /// Indicates the mobility of a provided service (e.g. 'static', 'dynamic').
    public var providerMobility: String?
    /// A review of the item.
    public var review: [Review]?
    /// The tangible thing generated by the service, e.g. a passport, permit, etc.
    public var serviceOutput: Thing?
    /// The type of service being offered, e.g. veterans' benefits, emergency relief, etc.
    public var serviceType: String?
    
    private enum CodingKeys: String, CodingKey {
        case aggregateRating
        case areaServed
        case audience
        case availableChannel
        case award
        case brand
        case broker
        case category
        case hasOfferCatalog
        case hoursAvailable
        case isRelatedTo
        case isSimilarTo
        case logo
        case offers
        case provider
        case providerMobility
        case review
        case serviceOutput
        case serviceType
    }
    
    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        
        if let value = try container.decodeIfPresent(SOAggregateRating.self, forKey: .aggregateRating) {
            self.aggregateRating = value
        }
        if let value = try container.decodeIfPresent(String.self, forKey: .areaServed) {
            self.areaServed = value
        }
        if let value = try container.decodeIfPresent(SOAudience.self, forKey: .audience) {
            self.audience = value
        }
        if let value = try container.decodeIfPresent(SOServiceChannel.self, forKey: .availableChannel) {
            self.availableChannel = value
        }
        if let value = try container.decodeIfPresent([String].self, forKey: .award) {
            self.award = value
        }
        if let value = try container.decodeBrandsOrOrganizationsIfPresent(forKey: .brand) {
            self.brand = value
        }
        if let value = try container.decodeOrganizationOrPersonIfPresent(forKey: .broker) {
            self.broker = value
        }
        if let value = try container.decodeTextOrThingIfPresent(forKey: .category) {
            self.category = value
        }
        if let value = try container.decodeIfPresent(SOOfferCatalog.self, forKey: .hasOfferCatalog) {
            self.hasOfferCatalog = value
        }
        if let value = try container.decodeIfPresent([SOOpeningHoursSpecification].self, forKey: .hoursAvailable) {
            self.hoursAvailable = value
        }
        if let value = try container.decodeProductsOrServicesIfPresent(forKey: .isRelatedTo) {
            self.isRelatedTo = value
        }
        if let value = try container.decodeProductsOrServicesIfPresent(forKey: .isSimilarTo) {
            self.isSimilarTo = value
        }
        if let value = try container.decodeImageObjectOrURLIfPresent(forKey: .logo) {
            self.logo = value
        }
        if let value = try container.decodeIfPresent([SOOffer].self, forKey: .offers) {
            self.offers = value
        }
        if let value = try container.decodeOrganizationOrPersonIfPresent(forKey: .provider) {
            self.provider = value
        }
        if let value = try container.decodeIfPresent(String.self, forKey: .providerMobility) {
            self.providerMobility = value
        }
        if let value = try container.decodeIfPresent([SOReview].self, forKey: .review) {
            self.review = value
        }
        if let value = try container.decodeIfPresent(SOThing.self, forKey: .serviceOutput) {
            self.serviceOutput = value
        }
        if let value = try container.decodeIfPresent(String.self, forKey: .serviceType) {
            self.serviceType = value
        }
        
        let superDecoder = try container.superDecoder()
        try super.init(from: superDecoder)
    }
    
    public override func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        
        if let value = self.aggregateRating as? SOAggregateRating {
            try container.encode(value, forKey: .aggregateRating)
        }
        if let value = self.areaServed as? String {
            try container.encode(value, forKey: .areaServed)
        }
        if let value = self.audience as? SOAudience {
            try container.encode(value, forKey: .audience)
        }
        if let value = self.availableChannel as? SOServiceChannel {
            try container.encode(value, forKey: .availableChannel)
        }
        if let value = self.award {
            try container.encode(value, forKey: .award)
        }
        if let value = self.brand {
            try container.encodeBrandsOrOrganizations(value, forKey: .brand)
        }
        if let value = self.broker {
            try container.encodeOrganizationOrPerson(value, forKey: .broker)
        }
        if let value = self.category {
            try container.encodeTextOrThing(value, forKey: .category)
        }
        if let value = self.hasOfferCatalog as? SOOfferCatalog {
            try container.encode(value, forKey: .hasOfferCatalog)
        }
        if let value = self.hoursAvailable as? [SOOpeningHoursSpecification] {
            try container.encode(value, forKey: .hoursAvailable)
        }
        if let value = self.isRelatedTo {
            try container.encodeProductsOrServices(value, forKey: .isRelatedTo)
        }
        if let value = self.isSimilarTo {
            try container.encodeProductsOrServices(value, forKey: .isSimilarTo)
        }
        if let value = self.logo {
            try container.encodeImageObjectOrURL(value, forKey: .logo)
        }
        if let value = self.offers as? [SOOffer] {
            try container.encode(value, forKey: .offers)
        }
        if let value = self.provider {
            try container.encodeOrganizationOrPerson(value, forKey: .provider)
        }
        if let value = self.providerMobility {
            try container.encode(value, forKey: .providerMobility)
        }
        if let value = self.review as? [SOReview] {
            try container.encode(value, forKey: .review)
        }
        if let value = self.serviceOutput as? SOThing {
            try container.encode(value, forKey: .serviceOutput)
        }
        if let value = self.serviceType {
            try container.encode(value, forKey: .serviceType)
        }
        
        let superEncoder = container.superEncoder()
        try super.encode(to: superEncoder)
    }
}
