import Foundation

public protocol SchemaPerson: SchemaThing, SchemaPersonOrURL, SchemaOrganizationOrPerson {
    var additionalName: String? { get set }
    var address: SchemaPostalAddressOrText? { get set }
    var affiliation: SchemaOrganization? { get set }
    var alumniOf: SchemaEducationalOrganizationOrOrganization? { get set }
    var award: String? { get set }
    var birthDate: SchemaDate? { get set }
    var birthPlace: SchemaPlace? { get set }
    var brand: SchemaBrandOrOrganization? { get set }
    var children: [SchemaPerson]? { get set }
    var colleague: SchemaPersonOrURL? { get set }
    var contactPoint: SchemaContactPoint? { get set }
    var deathDate: SchemaDate? { get set }
    var deathPlace: SchemaPlace? { get set }
    var duns: String? { get set }
    var email: String? { get set }
    var familyName: String? { get set }
    var faxNumber: String? { get set }
    var follows: [SchemaPerson]? { get set }
    var funder: SchemaOrganizationOrPerson? { get set }
    var gender: GenderOrText? { get set }
    var givenName: String? { get set }
    var globalLocationNumber: String? { get set }
    var hasOfferCatalog: SchemaOfferCatalog? { get set }
    var hasPOS: SchemaPlace? { get set }
    var height: SchemaDistanceOrQuantitativeValue? { get set }
    var homeLocation: SchemaContactPointOrPlace? { get set }
    var honorificPrefix: String? { get set }
    var honorificSuffix: String? { get set }
    var isicV4: String? { get set }
    var jobTitle: String? { get set }
    var knows: [SchemaPerson]? { get set }
    var makesOffer: [SchemaOffer]? { get set }
    var memberOf: [SchemaOrganizationOrProgramMembership]? { get set }
    var naics: String? { get set }
    var nationality: SchemaCountry? { get set }
    var netWorth: SchemaMonetaryAmountOrPriceSpecification? { get set }
    var owns: [SchemaProductOrService]? { get set }
    var parent: SchemaPerson? { get set }
    var performerIn: SchemaEvent? { get set }
    var relatedTo: [SchemaPerson]? { get set }
    var seeks: [SchemaDemand]? { get set }
    var sibling: SchemaPerson? { get set }
    var sponsor: SchemaOrganizationOrPerson? { get set }
    var spouse: SchemaPerson? { get set }
    var taxID: String? { get set }
    var telephone: String? { get set }
    var vatID: String? { get set }
    var weight: SchemaQuantitativeValue? { get set }
    var workLocation: SchemaContactPointOrPlace? { get set }
    var worksFor: [SchemaOrganization]? { get set }
}
