import Foundation

public protocol SchemaStructuredValue: SchemaIntangible, SchemaBooleanOrNumberOrStructuredValueOrText, SchemaEnumerationOrPropertyValueOrQualitativeValueOrQuantitativeValueOrStructuredValue {
    
}
