import Foundation

public enum SchemaType: String, CaseIterable {
    case action = "Action"
    case administrativeArea = "AdministrativeArea"
    case alignmentObject = "AlignmentObject"
    case answer = "Answer"
    case article = "Article"
    case audience = "Audience"
    case audioObject = "AudioObject"
    case brand = "Brand"
    case broadcastService = "BroadcastService"
    case comment = "Comment"
    case contactPoint = "ContactPoint"
    case country = "Country"
    case course = "Course"
    case courseInstance = "CourseInstance"
    case creativeWork = "CreativeWork"
    case dataCatalog = "DataCatalog"
    case dataDownload = "DataDownload"
    case dataFeed = "DataFeed"
    case dataFeedItem = "DataFeedItem"
    case dataset = "Dataset"
    case demand = "Demand"
    case distance = "Distance"
    case educationalOrganization = "EducationalOrganization"
    case entryPoint = "EntryPoint"
    case enumeration = "Enumeration"
    case event = "Event"
    case financialProduct = "FinancialProduct"
    case geoCoordinates = "GeoCoordinates"
    case geoShape = "GeoShape"
    case imageObject = "ImageObject"
    case intangible = "Intangible"
    case interactionCounter = "InteractionCounter"
    case itemList = "ItemList"
    case language = "Language"
    case listItem = "ListItem"
    case loanOrCredit = "LoanOrCredit"
    case locationFeatureSpecification = "LocationFeatureSpecification"
    case map = "Map"
    case mediaObject = "MediaObject"
    case monetaryAmount = "MonetaryAmount"
    case musicAlbum = "MusicAlbum"
    case musicComposition = "MusicComposition"
    case musicGroup = "MusicGroup"
    case musicPlaylist = "MusicPlaylist"
    case musicRecording = "MusicRecording"
    case musicRelease = "MusicRelease"
    case newsArticle = "NewsArticle"
    case occupation = "Occupation"
    case offer = "Offer"
    case offerCatalog = "OfferCatalog"
    case openingHoursSpecification = "OpeningHoursSpecification"
    case organization = "Organization"
    case ownershipInfo = "OwnershipInfo"
    case performingGroup = "PerformingGroup"
    case person = "Person"
    case photograph = "Photograph"
    case place = "Place"
    case postalAddress = "PostalAddress"
    case priceSpecification = "PriceSpecification"
    case product = "Product"
    case productModel = "ProductModel"
    case programMembership = "ProgramMembership"
    case propertyValue = "PropertyValue"
    case publicationEvent = "PublicationEvent"
    case qualitativeValue = "QualitativeValue"
    case quantitativeValue = "QuantitativeValue"
    case quantity = "Quantity"
    case question = "Question"
    case rating = "Rating"
    case repaymentSpecification = "RepaymentSpecification"
    case review = "Review"
    case service = "Service"
    case serviceChannel = "ServiceChannel"
    case softwareApplication = "SoftwareApplication"
    case structuredValue = "StructuredValue"
    case thing = "Thing"
    case typeAndQuantityNode = "TypeAndQuantityNode"
    case videoObject = "VideoObject"
    case warrantyPromise = "WarrantyPromise"
    case website = "Website"
    
    var type: SchemaCodable.Type {
        switch self {
        case .action: return Action.self
        case .administrativeArea: return AdministrativeArea.self
        case .alignmentObject: return AlignmentObject.self
        case .answer: return Answer.self
        case .article: return Article.self
        case .audience: return Audience.self
        case .audioObject: return AudioObject.self
        case .brand: return Brand.self
        case .broadcastService: return BroadcastService.self
        case .comment: return Comment.self
        case .contactPoint: return ContactPoint.self
        case .country: return Country.self
        case .course: return Course.self
        case .courseInstance: return CourseInstance.self
        case .creativeWork: return CreativeWork.self
        case .dataCatalog: return DataCatalog.self
        case .dataDownload: return DataDownload.self
        case .dataFeed: return DataFeed.self
        case .dataFeedItem: return DataFeedItem.self
        case .dataset: return Dataset.self
        case .demand: return Demand.self
        case .distance: return Distance.self
        case .educationalOrganization: return EducationalOrganization.self
        case .entryPoint: return EntryPoint.self
        case .enumeration: return Enumeration.self
        case .event: return Event.self
        case .financialProduct: return FinancialProduct.self
        case .geoCoordinates: return GeoCoordinates.self
        case .geoShape: return GeoShape.self
        case .imageObject: return ImageObject.self
        case .intangible: return Intangible.self
        case .interactionCounter: return InteractionCounter.self
        case .itemList: return ItemList.self
        case .language: return Language.self
        case .listItem: return ListItem.self
        case .loanOrCredit: return LoanOrCredit.self
        case .locationFeatureSpecification: return LocationFeatureSpecification.self
        case .map: return Map.self
        case .mediaObject: return MediaObject.self
        case .monetaryAmount: return MonetaryAmount.self
        case .musicAlbum: return MusicAlbum.self
        case .musicComposition: return MusicComposition.self
        case .musicGroup: return MusicGroup.self
        case .musicPlaylist: return MusicPlaylist.self
        case .musicRecording: return MusicRecording.self
        case .musicRelease: return MusicRelease.self
        case .newsArticle: return NewsArticle.self
        case .occupation: return Occupation.self
        case .offer: return Offer.self
        case .offerCatalog: return OfferCatalog.self
        case .openingHoursSpecification: return OpeningHoursSpecification.self
        case .organization: return Organization.self
        case .ownershipInfo: return OwnershipInfo.self
        case .performingGroup: return PerformingGroup.self
        case .person: return Person.self
        case .photograph: return Photograph.self
        case .place: return Place.self
        case .postalAddress: return PostalAddress.self
        case .priceSpecification: return PriceSpecification.self
        case .product: return Product.self
        case .productModel: return ProductModel.self
        case .programMembership: return ProgramMembership.self
        case .propertyValue: return PropertyValue.self
        case .publicationEvent: return PublicationEvent.self
        case .qualitativeValue: return QualitativeValue.self
        case .quantitativeValue: return QuantitativeValue.self
        case .quantity: return Quantity.self
        case .question: return Question.self
        case .rating: return Rating.self
        case .repaymentSpecification: return RepaymentSpecification.self
        case .review: return Review.self
        case .service: return Service.self
        case .serviceChannel: return ServiceChannel.self
        case .softwareApplication: return SoftwareApplication.self
        case .structuredValue: return StructuredValue.self
        case .thing: return Thing.self
        case .typeAndQuantityNode: return TypeAndQuantityNode.self
        case .videoObject: return VideoObject.self
        case .warrantyPromise: return WarrantyPromise.self
        case .website: return Website.self
        }
    }
}
