name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  SwiftActions:
    strategy:
      matrix:
        os: [macos-12, ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout Source
      uses: actions/checkout@v3

    - name: Swift Build
      uses: SwiftActions/SwiftBuild@main

    - name: Swift Test
      uses: SwiftActions/SwiftTest@main
